import useAuth from "@/hooks/useAuth";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { session } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (session) {
      router.replace(`/users/${session.user.id}`);
    } else {
      router.replace("/login");
    }
  }, [router, session]);

  return (
    <>
      <Head>
        <title>AMEDIA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}></main>
    </>
  );
}
