import Head from 'next/head'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import {useState} from "react";
import useAuth from "@/hooks/useAuth";
import {Credentials} from "@/types";
import { useRouter } from 'next/router'
import {supabase} from "@/lib/initSupabase";
import PrimaryButton from '@/components/Buttons/PrimaryButton/PrimaryButton.component'
import SecondaryButton from '@/components/Buttons/SecondaryButton/SecondaryButton.component'
import InputButton from '@/components/Buttons/InputButton/InputButton.component';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {signIn} = useAuth()
  const router = useRouter()
  const [userCredentials, setUserCredentials] = useState<Credentials | null>(null);
  function onUpdateUserCredentials(key: string, value: string){
    setUserCredentials(prevState => ({...prevState, [key]: value}))
  }

  function onSignIn(){
    if(!userCredentials){
      console.log('NO USER CREDENTIALS')
    }else{
      signIn(userCredentials).then(async () => {
        const { data: { user } } = await supabase.auth.getUser();
        if(user){
          await router.push(`/users/${user.id}`)
        }
      })
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.sectionConnexion}>
          <h1 className={styles.titleConnexion}>Se connecter</h1>
          <div className={styles.containerConnexion}>
            <div className={styles.contentConnexion}>
              <label htmlFor="">Email</label>
                <InputButton type="email" placeholder="Adresse mail" onChange={(event) => {onUpdateUserCredentials('email', event.target.value)}} />
            </div>
            <div className={styles.contentConnexion}>
              <label htmlFor="">Mot de passe</label>
              <InputButton type="password" placeholder="Mot de passe" onChange={(event) => {onUpdateUserCredentials('password', event.target.value)}} />
            </div>
            <div className={`${styles.contentConnexion} ${styles.connexionLinks}`}>
              <PrimaryButton title="Connexion" className={styles.connexionLink} onClick={() => {onSignIn()}} />
              <Link href="/register" className={styles.registerLink}>
                <SecondaryButton title="Créer un compte" />
              </Link>
              <a href="" className={styles.forgottenPasswordLink}>Mot de passe oublié ?</a>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
